language: node_js
services:
  - rabbitmq
node_js:
  - "9.1"
  - "11"
cache:
  directories:
  - "node_modules"
env:
  global:
    - CC_TEST_REPORTER_ID=def5a21b19d579295064355ef49518178fe4ee47f4e31ee18775df8f9ae7c96c
    - NODE_ENV=test
    - CT_URL=http://127.0.0.1:9000
    - CT_REGISTER_MODE=auto
    - API_VERSION=v1
    - STAMPERY_TOKEN=token
    - ELASTIC_URL=127.0.0.1:9000
    - RABBITMQ_URL=amqp://0.0.0.0:5672
    - HOST_IP=127.0.0.1
    - LOCAL_URL=http://127.0.0.1:4003
    - CT_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    - PORT=4003

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
