version: "3"
services:
  test:
    build: .
    container_name: doc-executor
    ports:
      - "4003:4003"
    env_file:
      - dev.env
    environment:
      NODE_ENV: dev
      API_VERSION: v1
      STAMPERY_TOKEN: token
      ELASTIC_URL: 127.0.0.1:9000
      RABBITMQ_URL: amqp://rabbitmq:5672
      HOST_IP: 127.0.0.1
      CT_REGISTER_MODE: auto
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      PORT: 4003
    command: develop
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
