apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        name: {name}
    spec:
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
        args:
          - start
        env:
          - name: NODE_ENV
            value: staging
          - name: NODE_PATH
            value: app/src
          - name: ELASTIC_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: ELASTIC_URI
          - name: STAMPERY_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: STAMPERY_TOKEN
          - name: RABBITMQ_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: RABBITMQ_URI

      restartPolicy: Always
